version: 2.1

defaults: &defaults
  working_directory: ~/placement-prototypes

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  upload:
    <<: *defaults
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/sync:
          arguments: |
            --exclude "*" \
            --include "*.js" \
            --include "*.css" \
            --include "notification.svg" \
            --cache-control "public,max-age=600"
          from: '.'
          to: 's3://placement-prototypes'

workflows:
  deploy-to-aws-s3:
    jobs:
      - upload:
          filters:
            branches:
              only: main
          context: 
            - aws-medwing # provides AWS access keys